# Generated by Django 5.1.1 on 2025-10-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
